name: Static Analysis

on: [push]

jobs:
  dusk-host:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: PHP version
        run: php -v
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Alayse PHPStun
        run: vendor/bin/phpstan analyse
